version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
    #commands:
      # - There are no build commands
  pre_build:
    commands:
      - pip3 install boto3
  build:
    commands:
      - python3 process.py

